### ISSUE TITLE
[Minor] На главной странице в header при нажатии на кнопку "Регистрация" цвет кнопки фиолетовый

### ISSUE THREAD

**Issue by MeriMakarova** [a-platform-for-designers/a-platform-for-designers-frontend#143]
**Приоритет:** низкий.
**Серьёзность:** minor. 

**Шаги воспроизведения:**

1. Открыть сайт по ссылке http://46.183.163.139/

**Ожидаемый результат:** На главной странице в header при нажатии на кнопку "Регистрация" цвет кнопки серый #E3E3E4
**Фактический результат:** На главной странице в header при нажатии на кнопку "Регистрация" цвет кнопки фиолетовый

**Окружение:**
ОС: Windows 10 Pro (версия 22H2, сборка 19045.3930)
Разрешение: 1920х1080
Браузер:
1. Google Chrome версия 120.0.6099.217 
3. Opera версия 106.0.4998.41
4. Firefox Browser версия 119.0.1
5. Safari 17 (Browserstack)

**Дополнительные материалы:**

https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/147608416/9931497e-066e-4af8-9f52-e935f7b28918

**Comment by nastya-kl** [comment]
Исправлено


https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/116949222/01097f4e-126b-479b-9adf-a333a9140ee4
