### ISSUE TITLE
[Minor] На главной странице в разделе о проекте при нажатии на кнопку "Найти дизайнеров" цвет кнопки фиолетовый

### ISSUE THREAD

**Issue by MeriMakarova** [a-platform-for-designers/a-platform-for-designers-frontend#144]
**Приоритет:** низкий.
**Серьёзность:** minor. 

**Шаги воспроизведения:**

1. Открыть сайт по ссылке http://46.183.163.139/

**Ожидаемый результат:** На главной странице в разделе о проекте при нажатии на кнопку "Найти дизайнеров" цвет кнопки серый #E3E3E4
**Фактический результат:** На главной странице в разделе о проекте при нажатии на кнопку "Найти дизайнеров" цвет кнопки фиолетовый

**Окружение:**
ОС: Windows 10 Pro (версия 22H2, сборка 19045.3930)
Разрешение: 1920х1080
Браузер:
1. Google Chrome версия 120.0.6099.217 
3. Opera версия 106.0.4998.41
4. Firefox Browser версия 119.0.1
5. Safari 17 (Browserstack)

**Дополнительные материалы:**

https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/147608416/08e09a6e-7a5a-42d7-a372-f0b721fda919

**Comment by nastya-kl** [comment]
Исправлено

https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/116949222/4f424796-1b53-4f42-99db-ae8b6678d439
