### ISSUE TITLE
[Minor] Карточка дизайнера. У пользователя с именем и фамилией из 40 символов имя и фамилия полностью не вмещаются и сдвигается вправо статус, "на сайте с" и лайки/подписчики

### ISSUE THREAD

**Issue by MeriMakarova** [a-platform-for-designers/a-platform-for-designers-frontend#146]
**Приоритет:** низкий.
**Серьёзность:** minor. 

**Предусловие:**
1. Открыть сайт по ссылке http://46.183.163.139/
2. Нажать на кнопку "Вход"
3. В инпут "E-mail" ввести: mnogo@yandex.ru
4. В инпут "Пароль" ввести: mnoya123
5. Нажать кнопку "Войти"

**Шаги воспроизведения:**

1. Нажать на аватарку пользователя в правой части header

**Ожидаемый результат:** У пользователя с именем и фамилией из 40 символов имя и фамилия полностью вмещаются, на странице ничего не сдвигается.
**Фактический результат:** У пользователя с именем и фамилией из 40 символов имя и фамилия полностью не вмещаются и сдвигается вправо статус, "на сайте с" и лайки/подписчики.

**Окружение:**
ОС: Windows 10 Pro (версия 22H2, сборка 19045.3930)
Разрешение: 1920х1080
Браузер:
1. Google Chrome версия 120.0.6099.217 
3. Opera версия 106.0.4998.41
4. Firefox Browser версия 119.0.1
5. Safari 17 (Browserstack)

**Дополнительные материалы:**

https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/147608416/922d7f2c-398f-4ec5-9027-eae324e4b401

**Comment by nastya-kl** [comment]
Исправлено

![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/116949222/eeb3ddd9-041b-42f5-b866-d9c2efbd43f2)
