### ISSUE TITLE
[Minor] ЛКД Профиль. У пользователя с именем и фамилией из 40 символов имя и фамилия показываются неполностью

### ISSUE THREAD

**Issue by MeriMakarova** [a-platform-for-designers/a-platform-for-designers-frontend#147]
**Приоритет:** средний.
**Серьёзность:** minor. 

**Предусловие:**
1. Открыть сайт по ссылке http://46.183.163.139/
2. Нажать на кнопку "Вход"
3. В инпут "E-mail" ввести: mnogo@yandex.ru
4. В инпут "Пароль" ввести: mnoya123
5. Нажать кнопку "Войти"

**Шаги воспроизведения:**

1. Нажать на аватарку пользователя в правой части header
2. Нажать на кнопку "Редактировать профиль"

**Ожидаемый результат:** У пользователя с именем и фамилией из 40 символов имя и фамилия показываются полностью

**Фактический результат:** У пользователя с именем и фамилией из 40 символов имя и фамилия показываются неполностью

**Окружение:**
ОС: Windows 10 Pro (версия 22H2, сборка 19045.3930)
Разрешение: 1920х1080
Браузер:
1. Google Chrome версия 120.0.6099.217 
3. Opera версия 106.0.4998.41
4. Firefox Browser версия 119.0.1
5. Safari 17 (Browserstack)

**Дополнительные материалы:**
![ЛКД Профиль  У пользователя с именем и фамилией из 40 символов имя и фамилия показываются неполностью](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/147608416/79088f9c-af6a-4b13-9712-f4cbf2e70876)

**Comment by nastya-kl** [comment]
Исправлено

![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/116949222/e5a02d3a-481d-4989-a5e6-d9b0862eed1d)
