### ISSUE TITLE
[Minor] Создание проекта. Если ввести в инпут  "Описание проекта" 500 символов, то в предпросмотре текст не переносится, заезжает за обложку и уезжает вправо за экран

### ISSUE THREAD

**Issue by MeriMakarova** [a-platform-for-designers/a-platform-for-designers-frontend#148]
**Приоритет:** средний.
**Серьёзность:** minor. 

**Предусловие:**
1. Открыть сайт по ссылке http://46.183.163.139/
2. Нажать на кнопку "Вход"
3. В инпут "E-mail" ввести: mnogo@yandex.ru
4. В инпут "Пароль" ввести: mnoya123
5. Нажать кнопку "Войти"

**Шаги воспроизведения:**

1. Нажать на аватарку пользователя в правой части header
2. Нажать на кнопку "Добавить проект"
3. В инпут "Название" вставить (50 символов): Уууууууууууууууууууууууууууууууууууууууууууууууууу
4. Добавить обложку
5. Добавить картинку
6. В инпут "Описание проекта" вставить (500 символов): Тууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууу
7. Нажать кнопку "Предпросмотр"

**Ожидаемый результат:** Текст описания проекта переносится, не заезжает за обложку и не уезжает вправо за экран.
**Фактический результат:**  Текст описания проекта не переносится, заезжает за обложку и уезжает вправо за экран.

**Окружение:**
ОС: Windows 10 Pro (версия 22H2, сборка 19045.3930)
Разрешение: 1920х1080
Браузер:
1. Google Chrome версия 120.0.6099.217 
8. Opera версия 106.0.4998.41
9. Firefox Browser версия 119.0.1
10. Safari 17 (Browserstack)

**Дополнительные материалы:**

https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/147608416/78d1b45c-075c-4640-9a3b-7bf496fbfdd7

**Comment by nastya-kl** [comment]
Исправлено

![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/116949222/68f7a4b5-eb4b-4ef6-ad23-369e8a6d36b5)

**Comment by nastya-kl** [comment]
Исправлено

![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/116949222/c4db77b3-2186-45cd-9c6e-8f281bc8fe43)
