### ISSUE TITLE
[Minor] Страница кейса. У пользователя с именем и фамилией из 40 символов имя и фамилия полностью не вмещаются и уезжают за обложку и картинки

### ISSUE THREAD

**Issue by MeriMakarova** [a-platform-for-designers/a-platform-for-designers-frontend#149]
**Приоритет:** средний.
**Серьёзность:** minor. 

**Предусловие:**
1. Открыть сайт по ссылке http://46.183.163.139/
2. Нажать на кнопку "Вход"
3. В инпут "E-mail" ввести: mnogo@yandex.ru
4. В инпут "Пароль" ввести: mnoya123
5. Нажать кнопку "Войти"

**Шаги воспроизведения:**

1. Нажать на аватарку пользователя в правой части header
2. Нажать на кнопку "Добавить проект"
3. В инпут "Название" вставить (50 символов): Уууууууууууууууууууууууууууууууууууууууууууууууууу
4. Добавить обложку
5. Добавить картинку
6. В инпут "Описание проекта" вставить (500 символов): Тууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууууу
7. Нажать кнопку "Опубликовать"
8.  Нажать на аватарку в правой части header
9. Выбрать в портфолио опубликованный кейс и нажать на него

**Ожидаемый результат:** Имя и фамилия полностью вмещаются и не уезжают за обложку и картинки
**Фактический результат:**  Имя и фамилия полностью не вмещаются и уезжают за обложку и картинки

**Окружение:**
ОС: Windows 10 Pro (версия 22H2, сборка 19045.3930)
Разрешение: 1920х1080
Браузер:
1. Google Chrome версия 120.0.6099.217 
10. Opera версия 106.0.4998.41
11. Firefox Browser версия 119.0.1
12. Safari 17 (Browserstack)

**Дополнительные материалы:**

https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/147608416/6e072279-1943-4f7c-90da-c675a209ace9

**Comment by nastya-kl** [comment]
Исправлено (в дизайне не обсуждали, пока оставила 1 строку и многоточие)

![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/116949222/591f3034-64f9-42b9-99ce-873713f99291)
