### ISSUE TITLE
[Minor] Вход. При вводе не верного пароля, не высвечивается текст ошибки “Неверный e-mail или пароль”.

### ISSUE THREAD

**Issue by sergeev-aleksey** [a-platform-for-designers/a-platform-for-designers-frontend#154]
**Приоритет:** средний.
**Серьёзность:** minor.

**Предусловие:**

1. Открыть сайт по ссылке http://46.183.163.139/
2. Пользователь зарегистрирован в системе.
3. Нажать на кнопку "Вход"

**Шаги воспроизведения:**

1. Ввести в поле Email данные при регистрации. К примеру: aleksei@yandex.ru
2. Ввести в поле Пароль, не верный пароль. К примеру: afrika1234
3. Нажать на кнопку "Вход"

**Ожидаемый результат:** Высвечивается текст ошибки под полем Пароль “Неверный e-mail или пароль”.

**Фактический результат:** Появляется всплывающее сообщение слева от экрана "Введены некорректные данные"

**Окружение:**
ОС: Windows 10 Pro (версия 22H2, сборка 19045.3930)
Разрешение: 1920х1080

Браузер:

Google Chrome версия 120.0.6099.217
Opera версия 106.0.4998.41
Firefox Browser версия 119.0.1
Safari 17 (Browserstack)

**Дополнительные материалы:**
![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/147543438/ba97fdbf-d384-4bad-82bf-5f8ca611f3d0)

**Comment by AnnaKharatova** [comment]
Исправлено
