### ISSUE TITLE
[Minor] Вход. При вводе не верного Email и пароля, не высвечивается текст ошибки “Неверный e-mail или пароль”. 

### ISSUE THREAD

**Issue by sergeev-aleksey** [a-platform-for-designers/a-platform-for-designers-frontend#156]
**Приоритет:** средний.
**Серьёзность:** minor.

**Предусловие:**

1. Открыть сайт по ссылке http://46.183.163.139/
2. Пользователь зарегистрирован в системе.
3. Нажать на кнопку "Вход"

**Шаги воспроизведения:**

1. Ввести в поле Email данные при регистрации. К примеру: aleksei@yandexx.ru
2. Ввести в поле Пароль, не верный пароль. К примеру: afrika123456
3. Нажать на кнопку "Вход"

**Ожидаемый результат:** Высвечивается текст ошибки под полем Пароль и Email “Неверный e-mail или пароль”.

**Фактический результат:** Появляется всплывающее сообщение слева от экрана "Введены некорректные данные"

**Окружение:**
ОС: Windows 10 Pro (версия 22H2, сборка 19045.3930)
Разрешение: 1920х1080

**Браузер:**

Google Chrome версия 120.0.6099.217
Opera версия 106.0.4998.41
Firefox Browser версия 119.0.1
Safari 17 (Browserstack)

**Дополнительные материалы:**

![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/147543438/a29b3f10-f2e1-4101-89b2-0bd7489afcbb)

**Comment by AnnaKharatova** [comment]
![Снимок](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/114444286/5511e47b-eba2-461f-b982-b873bc6d3ea3)
Исправлено
