### ISSUE TITLE
[Trivial] На главной странице в разделе "Категории дизайнеров" указано 3D-визуализаторы

### ISSUE THREAD

**Issue by MeriMakarova** [a-platform-for-designers/a-platform-for-designers-frontend#157]
**Приоритет:** низкий.
**Серьёзность:** trivial. 

**Шаги воспроизведения:**

1. Открыть сайт по ссылке http://46.183.163.139/

**Ожидаемый результат:** На главной странице в разделе "Категории дизайнеров" указано 3D-дизайнеры.

**Фактический результат:** На главной странице в разделе "Категории дизайнеров" указано 3D-визуализаторы.

**Окружение:**
ОС: Windows 10 Pro (версия 22H2, сборка 19045.3930)
Разрешение: 1920х1080
Браузер:
1. Google Chrome версия 120.0.6099.217 
6. Opera версия 106.0.4998.41
7. Firefox Browser версия 119.0.1
8. Safari 17 (Browserstack)

**Дополнительные материалы:**
![На главной странице в разделе Категории дизайнеров указано 3D-визуализаторы](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/147608416/a8b40541-e962-47bb-8b59-b8108f400af2)

**Comment by nastya-kl** [comment]
Исправлено

![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/116949222/08cda2f6-5821-4c7e-9193-31da68a6f02f)
