### ISSUE TITLE
[Minor] На главной странице в разделе "Лучшее на DesignCollab" ширина фона тегов с направлениями разной ширины, в зависимости от длины теста.

### ISSUE THREAD

**Issue by MeriMakarova** [a-platform-for-designers/a-platform-for-designers-frontend#158]
**Приоритет:** низкий.
**Серьёзность:** minor. 

**Шаги воспроизведения:**

1. Открыть сайт по ссылке http://46.183.163.139/

**Ожидаемый результат:** На главной странице в разделе "Лучшее на DesignCollab" ширина фона тегов с направлениями одинаковой ширины, вне зависимости от длины теста.

**Фактический результат:** На главной странице в разделе "Лучшее на DesignCollab" ширина фона тегов с направлениями разной ширины, в зависимости от длины теста.

**Окружение:**
ОС: Windows 10 Pro (версия 22H2, сборка 19045.3930)
Разрешение: 1920х1080
Браузер:
1. Google Chrome версия 120.0.6099.217 
6. Opera версия 106.0.4998.41
7. Firefox Browser версия 119.0.1
8. Safari 17 (Browserstack)

**Дополнительные материалы:**
![На главной странице в разделе Лучшее на DesignCollab ширина фона тегов с направлениями разной ширины, в зависимости от длины теста](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/147608416/8f2cfb2b-3b0b-459b-831b-8e190ec9062a)

**Comment by baibakovkir** [comment]
исправлено локально. При деплое будет добавлено на сайт
