### ISSUE TITLE
[Minor] Перелистывание кейсов на Главной странице клавишей "Tab" смещает дизайн карточки

### ISSUE THREAD

**Issue by MeriMakarova** [a-platform-for-designers/a-platform-for-designers-frontend#159]
**Приоритет:** низкий.
**Серьёзность:** minor. 

**Предусловие:**

1. Открыть сайт по ссылке http://46.183.163.139/

**Шаги воспроизведения:**

1. Долистать клавишей "Tab" до кейсов
2. Полистать кейсы "Tab'ом"

**Ожидаемый результат:** Можно переходить от одного кейса к другому нажимая клавишу "Tab"

**Фактический результат:** Смещается дизайн карточки

**Окружение:**
ОС: Windows 10 Pro (версия 22H2, сборка 19045.3930)
Разрешение: 1920х1080
Браузер:
1. Google Chrome версия 120.0.6099.217 
6. Opera версия 106.0.4998.41
7. Firefox Browser версия 119.0.1
8. Safari 17 (Browserstack)

**Дополнительные материалы:**

https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/147608416/fcdccd37-c983-4383-a35e-73d285e6118b

**Comment by baibakovkir** [comment]
исправлено локально. При деплое будет добавлено на сайт
