### ISSUE TITLE
[Minor] На главной странице в разделе "Лучшее на DesignCollab" в пагинации выбранная страница в рамке с серым фоном

### ISSUE THREAD

**Issue by MeriMakarova** [a-platform-for-designers/a-platform-for-designers-frontend#160]
**Приоритет:** низкий.
**Серьёзность:** minor. 

**Шаги воспроизведения:**

1. Открыть сайт по ссылке http://46.183.163.139/

**Ожидаемый результат:** На главной странице в разделе "Лучшее на DesignCollab" в пагинации выбранная страница в рамке с белым фоном

**Фактический результат:** На главной странице в разделе "Лучшее на DesignCollab" в пагинации выбранная страница в рамке с серым фоном

**Окружение:**
ОС: Windows 10 Pro (версия 22H2, сборка 19045.3930)
Разрешение: 1920х1080
Браузер:
1. Google Chrome версия 120.0.6099.217 
6. Opera версия 106.0.4998.41
7. Firefox Browser версия 119.0.1
8. Safari 17 (Browserstack)

**Дополнительные материалы:**
![На главной странице в разделе Лучшее на DesignCollab в пагинации выбранная страница в рамке с серым фоном](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/147608416/2e27690e-155e-4621-8019-c51626afbc33)

**Comment by nastya-kl** [comment]
Исправлено

![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/116949222/dbaf01a8-66d4-42a1-b71e-e13a7dc7f0a5)
