### ISSUE TITLE
[Major] ЛКД.Портфолио. Добавление проекта. В списке поля Инструменты отображаются 10 записей вместо 29

### ISSUE THREAD

**Issue by MeriMakarova** [a-platform-for-designers/a-platform-for-designers-frontend#173]
**Приоритет:** средний.
**Серьёзность:** major. 

**Предусловие:**
1. Открыть сайт по ссылке http://designcollab.pro/
2. Нажать на кнопку "Вход"
3. В инпут "E-mail" ввести: mark@mail.ru
4. В инпут "Пароль" ввести: markusha1
5. Нажать кнопку "Войти"

**Шаги воспроизведения:**

1. Нажать на аватарку пользователя в правой части header
2. Нажать на кнопку "Добавить проект"
3. Открыть список Инструментов

**Ожидаемый результат:** Раскрылся список с возможностью прокрутки из 29 (на 15.01.24) записей инструментов.
**Фактический результат:**  Раскрылся список с возможностью прокрутки из 10 записей инструментов.

**Окружение:**
ОС: Windows 10 Pro (версия 22H2, сборка 19045.3930)
Разрешение: 1920х1080
Браузер:
1. Google Chrome версия 120.0.6099.217 
10. Opera версия 106.0.4998.41
11. Firefox Browser версия 119.0.1
12. Safari 17 (Browserstack)

**Дополнительные материалы:**

https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/147608416/84391f87-daad-49a2-b702-fc68e98af423

**Comment by nastya-kl** [comment]
Исправлено

https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/116949222/654ee028-94ae-4103-9188-56cad10f6f82
