### ISSUE TITLE
[Blocker] Шаблон баг-репорта. Что-то нажала и ничего не работает! АААААААА!

### ISSUE THREAD

**Issue by MeriMakarova** [a-platform-for-designers/a-platform-for-designers-frontend#35]
**Серьёзность:** 
Blocker. _Блокирующая ошибка. Она делает невозможной всю последующую работу с программой. Для возобновления работы нужно исправить Blocker._
Critical. _Критическая ошибка. Нарушает работу основного функционала. Баг проявляется постоянно и делает невозможным использование основных функций программы._
Major. _Существенный баг. Затрудняет работу основного функционала или делает невозможным использование дополнительных функций. Пользоваться можно, элементы активны, но выполняют не то, что задумано._
Minor. _Незначительный баг. На функционал системы влияет относительно мало, затрудняет использование  дополнительных функций. Для обхода этого бага могут быть очевидные пути. Например, дефект в дизайне._
Trivial. _Тривиальный баг. Не влияет на функционал проекта, но ухудшает общее впечатление от работы с продуктом. Например, ошибка в тексте._

**Предусловие:**
Открыть сайт по ссылке url

**Шаги воспроизведения:**

1. Нажать что-то
2. Плакать
3. Удалить гитхаб

**Ожидаемый результат:** открылась форма такая-то
**Фактический результат:** открылась форма такая-то

**Окружение:**
ОС: Windows 10 Pro
Разрешение: 1920х1080
Браузер:
1. Google Chrome версия 119.0.6045.124
2. Opera версия 104.0.4944.54
3. Firefox Browser версия 119.0.1

**Дополнительные материалы:**
![dNcSXI1hIFA](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/147608416/abacc57a-3421-4c75-b8d8-0e2d7845107b)

**Comment by anahomma** [comment]
@MeriMakarova ААААА!

**Comment by anahomma** [comment]
УУУУУУУ!
