### ISSUE TITLE
 [Minor] Клик на Лого в footer на Главной странице не обновляет страницу и не ведёт в её начало

### ISSUE THREAD

**Issue by anahomma** [a-platform-for-designers/a-platform-for-designers-frontend#38]
**Серьёзность:** _Minor_ 
#### Предусловие:

1. Открыть тестовый стенд https://pre-dev-qa-11-11-2023--peppy-cucurucho-6ce816.netlify.app/
2.  Перейти на Главную страницу

#### Шаги воспроизведения:
1. Скроллом увести страницу вниз
2. Кликнуть на Лого в footer

**_Ожидаемый результат:_** Страница обновится и перелистнется в начало
**_Фактический результат:_** Логотип некликабельный

 **Окружение:**
ОС: Windows 10, Домашняя одноязычная х64
Разрешение: 1920х1080
Браузер: Google Chrome 119.0.6045.124

**Дополнительные материалы:** (не обращайте внимание на качество, всё выглядит норм) 
https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/127967149/49686b2c-f14c-41f3-8c34-acc031c3aa9c

**Comment by Kampel2012** [comment]
Fix: добавлен хендлер для клика, в зависимости от пути либо переключает роут, либо скроллит до 0,0

**Comment by anahomma** [comment]
Re-test: Done
