### ISSUE TITLE
[Major] Скролл Главной страницы скролит страницу "Дизайнеры" и наоборот

### ISSUE THREAD

**Issue by anahomma** [a-platform-for-designers/a-platform-for-designers-frontend#39]
**Серьёзность:**  _Major_ Существенный баг. 
#### Предусловие:

1. Открыть тестовый стенд https://pre-dev-qa-11-11-2023--peppy-cucurucho-6ce816.netlify.app/
2.  Открыть Главную страницу

#### Шаги воспроизведения:
1. Перейти на страницу "Дизайнеры" кликом в хедере
2. Пролистать страницу до конца
3. Перейти на Главную страницу кликом по лого в хедере

**_Ожидаемый результат:_** Открывается начало Главной страницы
**_Фактический результат:_** Открывается конец Главной страницы

 **Окружение:**
ОС: Windows 10, Домашняя одноязычная х64
Разрешение: 1920х1080
Браузер: Google Chrome 119.0.6045.124

**Дополнительные материалы:** 
[Скролл страниц Главная и Дизайнеры связаны.webm](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/127967149/965413f8-87df-4fbc-a53f-82c8578a4fda)

**Comment by Kampel2012** [comment]
Fix: Добавлен компонент Scroll To Top в App.
Коммит: https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/commit/70f60970605287117654e38fe0cba545707e9c9d

**Comment by anahomma** [comment]
Re-test: Done
