### ISSUE TITLE
 [Minor] Перелистывание кейсов на странице "Дизайнеры" клавишей "Tab" смещает дизайн карточки

### ISSUE THREAD

**Issue by anahomma** [a-platform-for-designers/a-platform-for-designers-frontend#41]
**Серьёзность:** _Minor_ 

#### Предусловие:

1. Открыть тестовый стенд https://pre-dev-qa-11-11-2023--peppy-cucurucho-6ce816.netlify.app/
2.  Перейти на страницу "Дизайнера"

#### Шаги воспроизведения:
1. Полистать кейсы "Tab'ом"

**_Ожидаемый результат:_** Можно переходить от одного кейса к другому нажимая клавишу "Tab"
**_Фактический результат:_** Смещается дизайн карточки

 **Окружение:**
ОС: Windows 10, Домашняя одноязычная х64
Разрешение: 1920х1080
Браузер: Google Chrome 119.0.6045.124

**Дополнительные материалы:** 
![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/127967149/fdbd172d-70e9-40cf-93e5-b2dfdad9d33c)

**Comment by anahomma** [comment]
Re-test: 
+ При нажатии Tab нет выделения каждого кейса. 
+ не выделяется кнопка "Написать"
[Нет видуализации перелистывания Tab'.webm](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/127967149/510c6f83-650b-4bbc-af4f-076be15be82b)

**Comment by Kampel2012** [comment]
![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/117913798/5066168b-72ce-4dff-b647-41b3b0558cb5)
поправил
