### ISSUE TITLE
[Minor] Кнопка "Сбросить фильтры" на странице "Дизайнеры" не иcчезает после клика на нее

### ISSUE THREAD

**Issue by anahomma** [a-platform-for-designers/a-platform-for-designers-frontend#42]
**Серьёзность:** _Minor_ 

#### Предусловие:

1. Открыть тестовый стенд https://pre-dev-qa-11-11-2023--peppy-cucurucho-6ce816.netlify.app/
2.  Перейти на страницу "Дизайнеры"

#### Шаги воспроизведения:
1.  Выбрать фильтры "Графические дизайнеры", "3D-Визуализаторы", "Все", "Визуальная концепция", "Adobe Photoshop"
2. Кликнуть кнопку "Сбросить фильтры"

**_Ожидаемый результат:_** Сбрасываются фильтры до дефолтного (пустого состояния), кнопка "Сбросить фильтры" **исчезает** 
**_Фактический результат:_** Сбрасываются фильтры до дефолтного (пустого состояния), кнопка "Сбросить фильтры" **остается**

 **Окружение:**
ОС: Windows 10, Домашняя одноязычная х64
Разрешение: 1920х1080
Браузер: Google Chrome 119.0.6045.124

**Дополнительные материалы:** 
[Кнопка Сбросить фильтры не иcчезает после клика на нее.webm](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/127967149/0c74c5e8-ed1d-47c0-b3a7-e3569beea1fd)

**Comment by Kampel2012** [comment]
Прошу поправить несостыковку в документации, кнопка остается всегда

**Comment by anahomma** [comment]
Re-test: Done
