### ISSUE TITLE
[Trivial] На главной странице в тегах с направлениями дизайна ошибки в слове Иллюстрация

### ISSUE THREAD

**Issue by MeriMakarova** [a-platform-for-designers/a-platform-for-designers-frontend#43]
**Серьёзность:** Trivial. 

**Шаги воспроизведения:**

1. Открыть тестовый стенд по ссылке https://pre-dev-qa-11-11-2023--peppy-cucurucho-6ce816.netlify.app/

**Ожидаемый результат:** В разделе "Теги направлений дизайна" тег с названием "Иллюстрация".
**Фактический результат:** В разделе "Теги направлений дизайна" тег с названием "ИллюстраТОциИ".

**Окружение:**
ОС: Windows 10 Pro
Разрешение: 1920х1080
Браузер:
1. Google Chrome версия 119.0.6045.124
2. Opera версия 104.0.4944.54
3. Firefox Browser версия 119.0.1
4. Safari 17 (Browserstack)

**Дополнительные материалы:**

![На главной странице в тегах с направлениями дизайна ошибка в слове Иллюстрации](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/147608416/857bbffb-7ac0-4e19-8d9f-2dab994bb3e6)

**Comment by Kampel2012** [comment]
Fix: опечатка 
![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/117913798/a2e0cc53-80b5-4581-a320-9016a82cb9d2)
