### ISSUE TITLE
[Trivial] На странице Дизайнеры неверно называется кнопка "Сбросить фильтры" 

### ISSUE THREAD

**Issue by anahomma** [a-platform-for-designers/a-platform-for-designers-frontend#44]
**Серьёзность:** _Trivial_ 

#### Предусловие:

1. Открыть тестовый стенд https://pre-dev-qa-11-11-2023--peppy-cucurucho-6ce816.netlify.app/

#### Шаги воспроизведения:
1.  Перейти на страницу "Дизайнеры"

**_Ожидаемый результат:_** кнопка "Сбросить фильтры"
**_Фактический результат:_** кнопка "Очистить фильтры"

 **Окружение:**
ОС: Windows 10, Домашняя одноязычная х64
Разрешение: 1920х1080
Браузер: Google Chrome 119.0.6045.124

**Дополнительные материалы:**  ![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/127967149/ab8d8dcb-62e5-44c9-8f45-331ed9f1fed1)

**Comment by Kampel2012** [comment]
Fix: изменил значение константы для кнопки 
![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/117913798/ed12aece-3bd5-4e7d-8fbc-b33ab61da2d5)

**Comment by anahomma** [comment]
Re-test: Done
