### ISSUE TITLE
[Trivial] На главной странице в тегах с направлениями дизайна отсутствует дефис и маленькая d в слове 3D-визуализация

### ISSUE THREAD

**Issue by MeriMakarova** [a-platform-for-designers/a-platform-for-designers-frontend#45]
**Серьёзность:** Trivial. 

**Шаги воспроизведения:**

1. Открыть тестовый стенд по ссылке https://pre-dev-qa-11-11-2023--peppy-cucurucho-6ce816.netlify.app/

**Ожидаемый результат:** В разделе "Теги направлений дизайна" тег с названием "3D-визуализация".
**Фактический результат:** В разделе "Теги направлений дизайна" тег с названием "3d визуализация".

**Окружение:**
ОС: Windows 10 Pro
Разрешение: 1920х1080
Браузер:
1. Google Chrome версия 119.0.6045.124
2. Opera версия 104.0.4944.54
3. Firefox Browser версия 119.0.1
4. Safari 17 (Browserstack)

**Дополнительные материалы:**
![На главной странице в тегах с направлениями дизайна отсутствует дефис и маленькая d в слове 3D-визуализация](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/147608416/d39d21fb-246d-42c0-b829-68b666c25b9d)

**Comment by Kampel2012** [comment]
Дубль issure https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/issues/51

**Comment by MeriMakarova** [comment]
Это не дубль. . Это разные разделы главной страницы. Баг не исправлен.
