### ISSUE TITLE
[Trivial] На главной странице в тегах с направлениями дизайна отсутствует дефис в слове Веб-дизайн

### ISSUE THREAD

**Issue by MeriMakarova** [a-platform-for-designers/a-platform-for-designers-frontend#46]
**Серьёзность:** Trivial. 

**Шаги воспроизведения:**

1. Открыть тестовый стенд по ссылке https://pre-dev-qa-11-11-2023--peppy-cucurucho-6ce816.netlify.app/

**Ожидаемый результат:** В разделе "Теги направлений дизайна" тег с названием "Веб-дизайн".
**Фактический результат:** В разделе "Теги направлений дизайна" тег с названием "Веб дизайн".

**Окружение:**
ОС: Windows 10 Pro
Разрешение: 1920х1080
Браузер:
1. Google Chrome версия 119.0.6045.124
2. Opera версия 104.0.4944.54
3. Firefox Browser версия 119.0.1
4. Safari 17 (Browserstack)

**Дополнительные материалы:**
![На главной странице в тегах с направлениями дизайна отсутствует дефис в слове Веб-дизайн](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/147608416/01a504f0-a728-45d5-85d5-fe716117996a)

**Comment by Kampel2012** [comment]
Fix: исправил
![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/117913798/b1124440-b736-4dfa-afff-a13ad41cfa06)

**Comment by MeriMakarova** [comment]
Это другой раздел. Баг не исправлен.
