### ISSUE TITLE
[Minor] Клик на ссылку "Дизайнеры" в футере со страницы "Дизайнеры" не обновляет страницу и не ведет в начало

### ISSUE THREAD

**Issue by anahomma** [a-platform-for-designers/a-platform-for-designers-frontend#47]
**Серьёзность:** _Minor_
#### Предусловие:

1. Открыть тестовый стенд https://pre-dev-qa-11-11-2023--peppy-cucurucho-6ce816.netlify.app/
2.  Перейти на страницу "Дизайнеры"

#### Шаги воспроизведения:
1. Пролистать страницу до конца
2. Кликнуть по ссылке "Дизайнеры" в футере

**_Ожидаемый результат:_** Страница обновится и перейдет в начало
**_Фактический результат:_** Страница не обновляется и не переходит в начало

 **Окружение:**
ОС: Windows 10, Домашняя одноязычная х64
Разрешение: 1920х1080
Браузер: Google Chrome 119.0.6045.124

**Дополнительные материалы:**

**Comment by Kampel2012** [comment]
Fix: добавлен компонент Scroll To Top на все первичные роуты. P.s. Обновления страницы не будет, но скролл будет всегда в топе

**Comment by anahomma** [comment]
Re-test: Done
