### ISSUE TITLE
[Minor] На главной странице колесом мыши скролл рывками с зависанием в Safari

### ISSUE THREAD

**Issue by MeriMakarova** [a-platform-for-designers/a-platform-for-designers-frontend#48]
**Серьёзность:** Minor. 

**Шаги воспроизведения:**

1. Открыть тестовый стенд по ссылке https://pre-dev-qa-11-11-2023--peppy-cucurucho-6ce816.netlify.app/

**Ожидаемый результат:** На главной странице колесом мыши плавный скролл.
**Фактический результат:** На главной странице колесом мыши скролл рывками с зависанием.

**Окружение:**
ОС: Windows 10 Pro
Разрешение: 1920х1080
Браузер: Safari 17 (Browserstack)

**Дополнительные материалы:**

https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/147608416/c33a5815-c01f-46de-89ce-43993ac957c9

**Comment by MeriMakarova** [comment]
Надо проверить на реальном устройстве. Т.к. возможно, что это баг эмуляции.

**Comment by Kampel2012** [comment]
На айфоне вроде норм, надеюсь это эмуляция - потому что дополнительных эффектов к скроллу мы пока не добавляли (ни плавность, ни вид скролла и тд)

**Comment by MeriMakarova** [comment]
На реальном устройстве не зависает. Закрываю баг.
