### ISSUE TITLE
[Minor] В header длина поля для поиска 240px.

### ISSUE THREAD

**Issue by MeriMakarova** [a-platform-for-designers/a-platform-for-designers-frontend#49]
**Серьёзность:** Minor. 

**Шаги воспроизведения:**

1. Открыть тестовый стенд по ссылке https://pre-dev-qa-11-11-2023--peppy-cucurucho-6ce816.netlify.app/

**Ожидаемый результат:** В header длина поля для поиска 360px.
**Фактический результат:** В header длина поля для поиска 240px.

**Окружение:**
ОС: Windows 10 Pro
Разрешение: 1920х1080
Браузер:
1. Google Chrome версия 119.0.6045.124
2. Opera версия 104.0.4944.54
3. Firefox Browser версия 119.0.1
4. Safari 17 (Browserstack)

**Дополнительные материалы:**

![В хедере поле для поиска длинной 240px](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/147608416/5764df13-4900-4a4e-a606-b1c493f8bb4a)

**Comment by Kampel2012** [comment]
Fix: поменял min-width на 360px 
![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/117913798/7bbfd77b-6c85-4a4f-9210-1debf389ff7c)
