### ISSUE TITLE
[Minor] В header авторизованного пользователя при наведении на аватар курсор не меняется со стрелки на указывающую руку

### ISSUE THREAD

**Issue by MeriMakarova** [a-platform-for-designers/a-platform-for-designers-frontend#50]
**Серьёзность:** Minor. 

**Шаги воспроизведения:**

1. Открыть тестовый стенд по ссылке https://pre-dev-qa-11-11-2023--peppy-cucurucho-6ce816.netlify.app/

**Ожидаемый результат:** В header авторизованного пользователя при наведении на аватар курсор меняется со стрелки на указывающую руку.
**Фактический результат:** В header авторизованного пользователя при наведении на аватар курсор не меняется со стрелки на указывающую руку.

**Окружение:**
ОС: Windows 10 Pro
Разрешение: 1920х1080
Браузер:
1. Google Chrome версия 119.0.6045.124
2. Opera версия 104.0.4944.54
3. Firefox Browser версия 119.0.1
4. Safari 17 (Browserstack)

**Дополнительные материалы:**

https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/147608416/cb4e9f98-4801-4ef0-b3d5-1b9560f9d969

**Comment by Kampel2012** [comment]
Fix: добавлен cursor: pointer на аватарку
