### ISSUE TITLE
[Trivial] На главной странице в разделе "Категории дизайнеров" отсутствует дефис и маленькая d в слове 3D-визуализаторы

### ISSUE THREAD

**Issue by MeriMakarova** [a-platform-for-designers/a-platform-for-designers-frontend#51]
**Серьёзность:** Trivial.

**Шаги воспроизведения:**

1. Открыть тестовый стенд по ссылке https://pre-dev-qa-11-11-2023--peppy-cucurucho-6ce816.netlify.app/

**Ожидаемый результат:** На главной странице в разделе "Категории дизаqнеров" название категории 3D-визуализаторы.
**Фактический результат:** На главной странице в разделе "Категории дизаqнеров" название категории 3d визуализаторы.

**Окружение:**
ОС: Windows 10 Pro
Разрешение: 1920х1080
Браузер:
1. Google Chrome версия 119.0.6045.124
2. Opera версия 104.0.4944.54
3. Firefox Browser версия 119.0.1
4. Safari 17 (Browserstack)

**Дополнительные материалы:**

![На главной странице в разделе Категории дизайнеров отсутствует дефис и маленькая d в слове 3D-визуализаторы](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/147608416/7a7ff127-0e5b-4107-a8fc-8ca1315e70eb)

**Comment by Kampel2012** [comment]
Fix: исправлена опечатка 
![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/117913798/ad17c3b2-cadf-4d15-a3bb-efa07f117997)

**Comment by MeriMakarova** [comment]
> Fix: исправлена опечатка ![image](https://user-images.githubusercontent.com/117913798/282408956-ad17c3b2-cadf-4d15-a3bb-efa07f117997.png)

Дефис не добавлен.
