### ISSUE TITLE
[Trivial] На главной странице в разделе Категории дизайнеров отсутствует дефис  в слове Веб-дизайнеры

### ISSUE THREAD

**Issue by MeriMakarova** [a-platform-for-designers/a-platform-for-designers-frontend#52]
**Серьёзность:** Trivial.

**Шаги воспроизведения:**

1. Открыть тестовый стенд по ссылке https://pre-dev-qa-11-11-2023--peppy-cucurucho-6ce816.netlify.app/

**Ожидаемый результат:** На главной странице в разделе "Категории дизаqнеров" название категории Веб-дизайнеры.
**Фактический результат:** На главной странице в разделе "Категории дизаqнеров" название категории Веб дизайнеры.

**Окружение:**
ОС: Windows 10 Pro
Разрешение: 1920х1080
Браузер:
1. Google Chrome версия 119.0.6045.124
2. Opera версия 104.0.4944.54
3. Firefox Browser версия 119.0.1
4. Safari 17 (Browserstack)

**Дополнительные материалы:**
![На главной странице в разделе Категории дизаqнеров отсутствует дефис  в слове Веб-дизайнеры](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/147608416/a5d91228-5fff-42dc-94e0-022c86661879)

**Comment by Kampel2012** [comment]
Fix: добавлен дефис 

![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/117913798/f88ab025-bda7-4878-8dc0-fce46be2f594)
