### ISSUE TITLE
[Trivial] На поп-апе входа в инпуте "Пароль" плейсхолдер Password

### ISSUE THREAD

**Issue by MeriMakarova** [a-platform-for-designers/a-platform-for-designers-frontend#53]
**Серьёзность:** Trivial.

**Предусловие:** открыть тестовый стенд по ссылке https://pre-dev-qa-11-11-2023--peppy-cucurucho-6ce816.netlify.app/

**Шаги воспроизведения:**

1. В правом углу header нажать кнопку "Вход"

**Ожидаемый результат:** На поп-апе входа в инпуте "Пароль" плейсхолдер Пароль
**Фактический результат:** На поп-апе входа в инпуте "Пароль" плейсхолдер Password.

**Окружение:**
ОС: Windows 10 Pro
Разрешение: 1920х1080
Браузер:
1. Google Chrome версия 119.0.6045.124
2. Opera версия 104.0.4944.54
3. Firefox Browser версия 119.0.1
4. Safari 17 (Browserstack)

**Дополнительные материалы:**
![На поп-апе входа в инпуте Пароль плейсхолдер Password](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/147608416/26edad79-1991-4834-85d5-76b50f56253e)

**Comment by Kampel2012** [comment]
Fix: изменен label для инпута 
![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/117913798/60ee4820-6397-4f78-a9e7-8edf7ce04853)
