### ISSUE TITLE
[Trivial] ЛКД.Портфолио.Добавление проекта. отсутствует плейсхолдер "Название проекта" для поля "Название"

### ISSUE THREAD

**Issue by ViSubb** [a-platform-for-designers/a-platform-for-designers-frontend#54]
Серьёзность:
Trivial

Предусловие:
1. Открыть сайт  https://pre-dev-qa-11-11-2023--peppy-cucurucho-6ce816.netlify.app/
2. Авторизоваться с ролью Дизайнер

Шаги воспроизведения:
1. Кликнуть на аватарку в правом верхнем углу
2. Кликнуть на кнопку "Редактировать профиль"
3. Перейти во вкладку "Портфолио" ЛКД
4. Начать добавление кейса по клику на кнопку "Добавить проект"

Ожидаемый результат: В первом поле "Название" плейсхолдер "Название проекта"
Фактический результат: В первом поле "Название" нет плейсхолдера "Название проекта" 

Окружение:
ОС: Windows 11

Браузер:
1. Firefox Browser версия 119.0.1

Дополнительные материалы:

![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/139245116/ba79b047-7dd4-44f8-ae82-bfc731e75c10)

[Макет](https://www.figma.com/file/FCilJnIgEBPeHHP5s2Gl73/DesignCollab?type=design&node-id=2438-40178&mode=design&t=NDmuvhhF3HgIt1wx-4)

**Comment by Kampel2012** [comment]
Fix: при маппинге инпутов добавил атрибут плейсхолдер 
![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/117913798/a1d49272-5c78-40c9-92ba-ac516a5ee5e3)
