### ISSUE TITLE
[Major] ЛКД.Портфолио.Добавление проекта. одна кнопка "Сохранить" вместо двух "Предпросмотр" и "Опубликовать проект"

### ISSUE THREAD

**Issue by ViSubb** [a-platform-for-designers/a-platform-for-designers-frontend#55]
Серьёзность: Major.

Предусловие: 
1. Открыть тестовый стенд по ссылке https://pre-dev-qa-11-11-2023--peppy-cucurucho-6ce816.netlify.app/
2. Авторизоваться с ролью Дизайнер

Шаги воспроизведения:

1. Кликнуть на аватарку в правом верхнем углу
2. Кликнуть на кнопку "Редактировать профиль"
3. Перейти во вкладку "Портфолио" ЛКД
4. Начать добавление кейса по клику на кнопку "Добавить проект"
5. Перейти вниз страницы добавления кейса

Ожидаемый результат: задизлейблиные кнопки "Предпросмотр" и "Опубликовать проект"
Фактический результат: задизлейблинная кнопка "Сохранить"

Окружение:
ОС: Windows 11

Браузер:

1. Firefox Browser версия 119.0.1

Дополнительные материалы:

![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/139245116/7892eabc-429f-4ac7-88af-4b7e344d0a14)

[Макет](https://www.figma.com/file/FCilJnIgEBPeHHP5s2Gl73/DesignCollab?type=design&node-id=2438-40178&mode=design&t=NDmuvhhF3HgIt1wx-4)

**Comment by Kampel2012** [comment]
Fix: Добавлена пара кнопок взамен кнопки сохранить, уведомление на предпросмотре, что находится в разработке
Commit: https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/commit/f3b7c1635ada2cab886a8954389f130c88d45384
