### ISSUE TITLE
[Trivial] ЛКД.Портфолио.Добавление проекта. под полем "Обложка" подпись "Рекомендуемая ширина: 920 px" вместо "Рекомендуемое разрешение: 330 x 240 px"

### ISSUE THREAD

**Issue by ViSubb** [a-platform-for-designers/a-platform-for-designers-frontend#56]
Серьёзность:
Trivial

Предусловие:

1. Открыть сайт https://pre-dev-qa-11-11-2023--peppy-cucurucho-6ce816.netlify.app/
2. Авторизоваться с ролью Дизайнер

Шаги воспроизведения:

1. Кликнуть на аватарку в правом верхнем углу
2. Кликнуть на кнопку "Редактировать профиль"
3. Перейти во вкладку "Портфолио" ЛКД
4. Начать добавление кейса по клику на кнопку "Добавить проект"

Ожидаемый результат: Напротив поля "Обложка" под кнопкой "Загрузить обложку" подпись "Рекомендуемое разрешение: 330 x 240 px"
Фактический результат: Напротив поля "Обложка" под кнопкой "Загрузить обложку" подпись "Рекомендуемая ширина: 920 px"

Окружение:
ОС: Windows 11

Браузер:

1. Firefox Browser версия 119.0.1

Дополнительные материалы:

![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/139245116/dfe0f1c0-6463-487f-8b66-4bc86b9e399d)

[Макет](https://www.figma.com/file/FCilJnIgEBPeHHP5s2Gl73/DesignCollab?type=design&node-id=2438-40186&mode=design&t=NDmuvhhF3HgIt1wx-4)

**Comment by Kampel2012** [comment]
Fix: исправлено описание обложки 
![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/117913798/801ee1d1-c920-4783-95b1-cdf8815702c9)
