### ISSUE TITLE
[Trivial] ЛКД.Портфолио.Добавление проекта. Отсутствует плейсхолдер в поле "Срок реализации"

### ISSUE THREAD

**Issue by ViSubb** [a-platform-for-designers/a-platform-for-designers-frontend#57]
Серьёзность:
Trivial

Предусловие:

1. Открыть сайт https://pre-dev-qa-11-11-2023--peppy-cucurucho-6ce816.netlify.app/
2. Авторизоваться с ролью Дизайнер

Шаги воспроизведения:

1. Кликнуть на аватарку в правом верхнем углу
2. Кликнуть на кнопку "Редактировать профиль"
3. Перейти во вкладку "Портфолио" ЛКД
4. Начать добавление кейса по клику на кнопку "Добавить проект"

Ожидаемый результат: Поле "Срок реализации" содержит плейсхолдер "Сколько времени делали проект" 
Фактический результат: В поле "Срок реализации" нет плейсхолдеров

Окружение:
ОС: Windows 11

Браузеры:

1. Firefox Browser версия 119.0.1

Дополнительные материалы:

![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/139245116/5f2e621b-ad09-420c-ba21-6dc59c72aca2)

[Макет](https://www.figma.com/file/FCilJnIgEBPeHHP5s2Gl73/DesignCollab?type=design&node-id=2438-40186&mode=design&t=NDmuvhhF3HgIt1wx-4)

**Comment by Kampel2012** [comment]
Fix: при маппинге инпутов был добавлен атрибут placeholder
