### ISSUE TITLE
[Minor] ЛКД.Портфолио. Не работает call to action

### ISSUE THREAD

**Issue by ViSubb** [a-platform-for-designers/a-platform-for-designers-frontend#59]
Серьёзность:
Minor

Предусловие:

1. Открыть сайт https://pre-dev-qa-11-11-2023--peppy-cucurucho-6ce816.netlify.app/
2. Авторизоваться с ролью Дизайнер

Шаги воспроизведения:

1. Кликнуть на аватарку в правом верхнем углу
2. Кликнуть на кнопку "Редактировать профиль"
3. Перейти во вкладку "Портфолио" ЛКД
4. Клик на большой плюс call to action

Ожидаемый результат: Открылась страница добавления кейсов
Фактический результат: Ничего не происходит

Окружение:
ОС: Windows 11

Браузер:

1. Firefox Browser версия 119.0.1

Дополнительные материалы:

![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/139245116/3945dbb9-a67f-4314-a41c-941ccd444d0b)

**Comment by Kampel2012** [comment]
Fix: добавлен обработчик события клика аналогичный кнопке. Добавлены курсор поинтер и кэф прозрачности 0.9 при наведении.
