### ISSUE TITLE
[Minor] ЛКД.Портфолио.Добавление проекта. В списке поля Сфера отображаются 10 записей вместо 49 из таблицы сфер

### ISSUE THREAD

**Issue by ViSubb** [a-platform-for-designers/a-platform-for-designers-frontend#63]
Серьёзность: Minor.

Предусловие:

1. Открыть тестовый стенд по ссылке https://pre-dev-qa-11-11-2023--peppy-cucurucho-6ce816.netlify.app/
2. Авторизоваться с ролью Дизайнер

Шаги воспроизведения:

1. Кликнуть на аватарку в правом верхнем углу
2. Кликнуть на кнопку "Редактировать профиль"
3. Перейти во вкладку "Портфолио" ЛКД
4. Начать добавление кейса по клику на кнопку "Добавить проект"
5. Клик в поле Сфера

Ожидаемый результат: Раскрылся список с возможностью прокрутки из 49 (на 12.11.23) записей сфер
Фактический результат: Раскрылся список из 10 первых записей таблицы Сферы (ниже ссылка)

Окружение:
ОС: Windows 11

Браузер:

1. Firefox Browser версия 119.0.1

Дополнительные материалы:

https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/139245116/142cdad2-bdf2-4674-bae1-303768c6a3c9

[Ссылка на таблицу Сфер](https://docs.google.com/spreadsheets/d/1Rtl4FaMLZYFvD2Kc-vdKId1kPz4h8obLIp7_PjEel7I/edit?usp=drive_link)

**Comment by Kampel2012** [comment]
Fix: исправлена ссылка на константу сфер теперь LISTS.LIST_SPHERES
