### ISSUE TITLE
[Minor] ЛКД.Портфолио.Добавление проекта. В списке поля Инструменты отображаются 10 записей вместо 69 из таблицы инструментов

### ISSUE THREAD

**Issue by ViSubb** [a-platform-for-designers/a-platform-for-designers-frontend#64]
Серьёзность: Minor.

Предусловие:

1. Открыть тестовый стенд по ссылке https://pre-dev-qa-11-11-2023--peppy-cucurucho-6ce816.netlify.app/
2. Авторизоваться с ролью Дизайнер

Шаги воспроизведения:

1. Кликнуть на аватарку в правом верхнем углу
2. Кликнуть на кнопку "Редактировать профиль"
3. Перейти во вкладку "Портфолио" ЛКД
4. Начать добавление кейса по клику на кнопку "Добавить проект"
5. Клик в поле Инструменты

Ожидаемый результат: Раскрылся список с возможностью прокрутки из 69 (на 12.11.23) записей инструментов
Фактический результат: Раскрылся список из 10 первых записей таблицы инструменты (ниже ссылка)

Окружение:
ОС: Windows 11

Браузер:

1. Firefox Browser версия 119.0.1

Дополнительные материалы:

https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/139245116/f8759574-5a5b-4ca6-b505-5593555f0554

[Ссылка на таблицу Сфер](https://docs.google.com/spreadsheets/d/1JcwMqbEMEXvFkj9t4VJbRXbWnm8jcrhFJBEFpmjbVhU/edit?usp=sharing)

**Comment by Kampel2012** [comment]
Fix: исправлена ссылка до константы со списком инструментов. Теперь берется LISTS.LIST_TOOLS
