### ISSUE TITLE
[Minor] ЛКД.Портфолио.Добавить проект. Поле "Обложка" принимает форматы вне описанных в ТЗ

### ISSUE THREAD

**Issue by ViSubb** [a-platform-for-designers/a-platform-for-designers-frontend#65]
Серьёзность: Minor.

Предусловие:

1. Открыть тестовый стенд по ссылке https://pre-dev-qa-11-11-2023--peppy-cucurucho-6ce816.netlify.app/
2. Авторизоваться с ролью Дизайнер
3. Кликнуть на аватарку в правом верхнем углу
4. Кликнуть на кнопку "Редактировать профиль"
5. Перейти во вкладку "Портфолио" ЛКД
6. Начать добавление кейса по клику на кнопку "Добавить проект"

Шаги воспроизведения:

1. Сохранить на ПК изображения в форматах из списка: *jpe ;*. gif ;*. svgz ;*. drw ;*. pct ;*. psp ;* xcf ;*. psd . (ниже в доп.материалах)
2. Клик по кнопке "Загрузить обложку"
3. По очереди выбрать файлы из списка

Ожидаемый результат: Ошибка "Неверный загружаемый формат"
Фактический результат: Картинки с расширением из списка успешно загружены

Окружение:
ОС: Windows 11

Браузер:

1. Firefox Browser версия 119.0.1

Дополнительные материалы:
[картинки в загруженных форматах.zip](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/files/13329140/default.zip)

https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/139245116/d07e5462-41b1-4c7b-abd3-0f97962e8b75

**Comment by Kampel2012** [comment]
Баг касается браузера Firefox-a, **требует детального изучения**

[ ]
