### ISSUE TITLE
[Minor] ЛКД.Портфолио.Добавление проекта. В списке "Инструменты" можно выбрать больше 5 инструментов

### ISSUE THREAD

**Issue by ViSubb** [a-platform-for-designers/a-platform-for-designers-frontend#67]
Серьёзность: Minor.

Предусловие:

1. Открыть тестовый стенд по ссылке https://pre-dev-qa-11-11-2023--peppy-cucurucho-6ce816.netlify.app/
2. Авторизоваться с ролью Дизайнер
3. Кликнуть на аватарку в правом верхнем углу
4. Кликнуть на кнопку "Редактировать профиль"
5. Перейти во вкладку "Портфолио" ЛКД
6. Начать добавление кейса по клику на кнопку "Добавить проект"

Шаги воспроизведения:

1. Выбрать в списке поля "Инструменты" 6 программ

Ожидаемый результат: После 5 выбранных программ выбор недоступен
Фактический результат: Выбор 6 программ осуществляется

Окружение:
ОС: Windows 11

Браузер:

1. Firefox Browser версия 119.0.1

Дополнительные материалы:

![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/139245116/cb3e0777-6fb4-4c5c-9014-1a6039f91850)

**Comment by Kampel2012** [comment]
Fix: огранили кол-во до 5
