### ISSUE TITLE
[Minor] Регистрация. При вводе в поле "E-mail" строки со знаком подчеркивания в доменной части: peubruffuddala@yop_mail.com, система не принимает это значение.

### ISSUE THREAD

**Issue by VyacheslavKu** [a-platform-for-designers/a-platform-for-designers-frontend#69]
Серьёзность: Minor.

Предусловие:

Открыть тестовый стенд по ссылке https://pre-dev-qa-11-11-2023--peppy-cucurucho-6ce816.netlify.app/

Шаги воспроизведения:

1. Нажать кнопку "Регистрация"
2. Выбрать роль "Заказчик"
3. В поле "E-mail" ввести данные: peubruffuddala@yop_mail.com

Ожидаемый результат: Система принимает строку со знаком подчеркивания в доменной части
Фактический результат: Система не принимает строку со знаком подчеркивания в доменной части

Окружение:
ОС: Windows 10 Pro 19042.2965
Разрешение: 1920х1080
Браузер:
1. Google Chrome Версия 119.0.6045.124 (64 бит)
2. Яндекс Браузер Версия 23.9.4.837 (64-bit)
3. Mozilla Firefox Версия 119.0.1 (64-разрядный)

Дополнительные материалы:
![2023-11-13_11-15-15](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/145761560/1befc105-0a7b-48de-9b5a-7b7e29b79efc)

**Comment by Kampel2012** [comment]
Стандарты электронной почты, определенные в RFC 5322 и RFC 5321, не разрешают использование символа подчеркивания (_) в доменной части адреса электронной почты. Доменная часть адреса (часть после символа "@") может содержать только буквы (A-Z, a-z), цифры (0-9), дефисы (-) и точки (.).
