### ISSUE TITLE
[Trivial] Регистрация. При вводе данных абв@маил.ру, в поле "E-mail", не соответствующих формату, текст ошибки "Введите корректный e-mail вида abcde@bk.ru"

### ISSUE THREAD

**Issue by VyacheslavKu** [a-platform-for-designers/a-platform-for-designers-frontend#70]
Серьёзность: Trivial.

Предусловие:

Открыть тестовый стенд по ссылке https://pre-dev-qa-11-11-2023--peppy-cucurucho-6ce816.netlify.app/

Шаги воспроизведения:

1. Нажать кнопку "Регистрация"
2. Выбрать роль "Заказчик"
3. В поле "E-mail" ввести данные: абв@маил.ру

Ожидаемый результат: Поле подсвечивается красным под полем красный текст ошибки "Введите e-mail в формате abcde@bk.ru"
Фактический результат: Поле подсвечивается красным под полем красный текст ошибки "Введите корректный e-mail вида abcde@bk.ru"

Окружение:
ОС: Windows 10 Pro 19042.2965
Разрешение: 1920х1080
Браузер:
1. Google Chrome Версия 119.0.6045.124 (64 бит)
2. Яндекс Браузер Версия 23.9.4.837 (64-bit)
3. Mozilla Firefox Версия 119.0.1 (64-разрядный)

Дополнительные материалы:
![2023-11-13_11-20-06](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/145761560/ddab09ff-7df0-424e-a980-c4b702c0082a)

**Comment by Kampel2012** [comment]
Fix: в хуке поправил описание ошибки p.s. вынести в константы отдельно
![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/117913798/1dd4f878-9c7f-4b94-8e53-b146eed5109c)

**Comment by VyacheslavKu** [comment]
Текст ошибки согласно https://docs.google.com/document/d/1djqhVURdK-vFzcNCZxJ9iP_KmujF6kky2RCCoORn6zI/edit : "Введите e-mail в формате abcde@bk.ru"

**Comment by AnnaKharatova** [comment]
![Снимок6](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/114444286/30bd200d-7304-40b3-87fc-c76d777b901e)
Исправлено
