### ISSUE TITLE
[Minor] Регистрация. При вводе данных 款高自由探索@ya.ru, в поле "E-mail", не соответствующих формату, поле принимает введённые данные.

### ISSUE THREAD

**Issue by VyacheslavKu** [a-platform-for-designers/a-platform-for-designers-frontend#71]
Серьёзность: Minor.

Предусловие:

Открыть тестовый стенд по ссылке https://pre-dev-qa-11-11-2023--peppy-cucurucho-6ce816.netlify.app/

Шаги воспроизведения:

Нажать кнопку "Регистрация"
Выбрать роль "Заказчик"
В поле "E-mail" ввести данные: 款高自由探索@ya.ru
Ожидаемый результат: Поле подсвечивается красным под полем красный текст ошибки "Введите e-mail в формате abcde@bk.ru"
Фактический результат: Поле принимает введённые данные.

Окружение:
ОС: Windows 10 Pro 19042.2965
Разрешение: 1920х1080
Браузер:

Google Chrome Версия 119.0.6045.124 (64 бит)
Яндекс Браузер Версия 23.9.4.837 (64-bit)
Mozilla Firefox Версия 119.0.1 (64-разрядный)
Дополнительные материалы:
![2023-11-13_11-29-00](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/145761560/d3104138-20e3-46cd-86d1-2115eec15058)

**Comment by Kampel2012** [comment]
fix: Поменяли паттерн с международного эмейла на только с латинскими (-5ккк потенциальных пользователей) ![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/117913798/9188a156-3bdc-407e-bca6-29a1d4811089)

**Comment by AnnaKharatova** [comment]
![Снимок6](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/114444286/3badc608-1acf-4efe-ae44-6187b34e89ce)
Исправлено
