### ISSUE TITLE
[Trivial] Регистрация. При вводе данных bIeO_FqogehcE0_XKlO1KWmITuMiW4pIe%, в поле "Пароль", не соответствующих формату, текст ошибки "В поле должно быть максимум 32 символов"

### ISSUE THREAD

**Issue by VyacheslavKu** [a-platform-for-designers/a-platform-for-designers-frontend#72]
Серьёзность: Trivial.

Предусловие:

Открыть тестовый стенд по ссылке https://pre-dev-qa-11-11-2023--peppy-cucurucho-6ce816.netlify.app/

Шаги воспроизведения:

1. Нажать кнопку "Регистрация"
2. Выбрать роль "Заказчик"
3. В поле "Пароль" ввести данные: bIeO_FqogehcE0_XKlO1KWmITuMiW4pIe

Ожидаемый результат: Поле подсвечивается красным под полем красный текст ошибки "В поле должно быть максимум 32 символа"
Фактический результат: Поле подсвечивается красным под полем красный текст ошибки "В поле должно быть максимум 32 символов"

Окружение:
ОС: Windows 10 Pro 19042.2965
Разрешение: 1920х1080
Браузер:
1. Google Chrome Версия 119.0.6045.124 (64 бит)
2. Яндекс Браузер Версия 23.9.4.837 (64-bit)
3. Mozilla Firefox Версия 119.0.1 (64-разрядный)

Дополнительные материалы:
![2023-11-13_11-46-46](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/145761560/dfef04d0-f6ea-4d7a-beb5-9fad7bdddccb)
Аналогичная ошибка при вводе в поле "Пароль" 34 символа: bIeO_FqogehcE0_XKlO1KWmITuMiW4pIe% и 40 символов: l4CHG$PQBRSjRC@6Ey9unv*BEstTTEKQGmFodZpM

**Comment by Kampel2012** [comment]
Fix: написан алгоритм определения правильный текст 
![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/117913798/c8f378e9-16b7-4ca6-8465-2c2c178a8fff)

**Comment by AnnaKharatova** [comment]
![Снимок4](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/114444286/e1712ca9-439a-4ef6-b9f5-4ddd3045a5bd)
Исправлено
