### ISSUE TITLE
[Minor] Регистрация. При вводе данных абырвалгабырвалг, в поле "Пароль", не соответствующих формату, поле принимает введённые данные.

### ISSUE THREAD

**Issue by VyacheslavKu** [a-platform-for-designers/a-platform-for-designers-frontend#73]
Серьёзность: Minor.

Предусловие:

Открыть тестовый стенд по ссылке https://pre-dev-qa-11-11-2023--peppy-cucurucho-6ce816.netlify.app/

Шаги воспроизведения:

1. Нажать кнопку "Регистрация"
2. Выбрать роль "Заказчик"
3. В поле "Пароль" ввести данные: абырвалгабырвалг

Ожидаемый результат: Поле подсвечивается красным под полем красный текст ошибки "Используйте латиницу, цифры или специальные символы"
Фактический результат: Поле принимает введённые данные.

Окружение:
ОС: Windows 10 Pro 19042.2965
Разрешение: 1920х1080
Браузер:
1. Google Chrome Версия 119.0.6045.124 (64 бит)
2. Яндекс Браузер Версия 23.9.4.837 (64-bit)
3. Mozilla Firefox Версия 119.0.1 (64-разрядный)

Дополнительные материалы:
![2023-11-13_11-53-42](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/145761560/19730781-dc64-43bb-8afd-a17391a46d80)

**Comment by Kampel2012** [comment]
![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/117913798/80396770-f32b-4816-adab-50e117be8d6f)
Fix: паттерн

**Comment by AnnaKharatova** [comment]
![Снимок3](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/114444286/3166ba70-1c24-45a7-8b88-12f5109946ec)
Исправлено
