### ISSUE TITLE
[Minor] Регистрация. При вводе данных 款高自由探索款高自由探索, в поле "Пароль", не соответствующих формату, поле принимает введённые данные.

### ISSUE THREAD

**Issue by VyacheslavKu** [a-platform-for-designers/a-platform-for-designers-frontend#74]
Серьёзность: Minor.

Предусловие:

Открыть тестовый стенд по ссылке https://pre-dev-qa-11-11-2023--peppy-cucurucho-6ce816.netlify.app/

Шаги воспроизведения:

1. Нажать кнопку "Регистрация"
2. Выбрать роль "Заказчик"
3. В поле "Пароль" ввести данные: 款高自由探索款高自由探索

Ожидаемый результат: Поле подсвечивается красным под полем красный текст ошибки "Используйте латиницу, цифры или специальные символы"
Фактический результат: Поле принимает введённые данные.

Окружение:
ОС: Windows 10 Pro 19042.2965
Разрешение: 1920х1080
Браузер:
1. Google Chrome Версия 119.0.6045.124 (64 бит)
2. Яндекс Браузер Версия 23.9.4.837 (64-bit)
3. Mozilla Firefox Версия 119.0.1 (64-разрядный)

Дополнительные материалы:
![2023-11-13_11-57-51](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/145761560/c540794f-6695-4fd3-b77b-b936139d7c5e)

**Comment by Kampel2012** [comment]
Fix: изменил паттерн проверки пароля ![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/117913798/3643a11c-ade0-4068-9e07-e92afbd32beb)

**Comment by AnnaKharatova** [comment]
![Снимок2](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/114444286/d265b6af-3055-4464-8cfe-30a50418b03e)
Исправлено
