### ISSUE TITLE
[Trivial] Регистрация. Клик на иконку "закрытый глаз" в поле "Пароль" показывает введенный пароль поля "Пароль",  иконка меняется на "открытый глаз" в поле "Пароль"

### ISSUE THREAD

**Issue by VyacheslavKu** [a-platform-for-designers/a-platform-for-designers-frontend#75]
Серьёзность: Trivial.

Предусловие:

Открыть тестовый стенд по ссылке https://pre-dev-qa-11-11-2023--peppy-cucurucho-6ce816.netlify.app/

Шаги воспроизведения:

1. Нажать кнопку "Регистрация"
2. Выбрать роль "Заказчик"
3. В поле "Пароль" ввести данные: dA6vtlVHFbYacV-8
4. В поле "Подтвердите пароль" ввести данные: dA6vtlVHFbYacV-8
5. Кликнуть на иконку "закрытый глаз" в поле "Пароль"

Ожидаемый результат: Кликнуть на иконку "закрытый глаз" в поле "Пароль" показывает введенные пароли полей "Пароль" и "Подтвердите пароль", иконка меняется на "открытый глаз" в обоих полях
Фактический результат: Кликнуть на иконку "закрытый глаз" в поле "Пароль" показывает введенный пароль поля "Пароль",  иконка меняется на "открытый глаз" в поле "Пароль"

Окружение:
ОС: Windows 10 Pro 19042.2965
Разрешение: 1920х1080
Браузер:
1. Google Chrome Версия 119.0.6045.124 (64 бит)
2. Яндекс Браузер Версия 23.9.4.837 (64-bit)
3. Mozilla Firefox Версия 119.0.1 (64-разрядный)

Дополнительные материалы:
![2023-11-13_12-04-18](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/145761560/90363421-0276-4a75-8dee-f7e9c05a704c)
Аналогичные ошибки при клике на иконку "открытый глаз" в поле "Пароль" и иконку "закрытый глаз" в полях "Подтвердите пароль" и "Пароль"

**Comment by Kampel2012** [comment]
В ТЗ Ф-4 Ф-5 не нашел упоминания, о том, что два поля должны ссылаться на одно и то же состояние
