### ISSUE TITLE
[Minor] (Авторизация). При вводе пробелов в поле "Пароль" не появляется сообщение об ошибке.

### ISSUE THREAD

**Issue by sergeev-aleksey** [a-platform-for-designers/a-platform-for-designers-frontend#76]
Серьёзность: Minor.

Предусловие:

Открыть тестовый стенд по ссылке https://pre-dev-qa-11-11-2023--peppy-cucurucho-6ce816.netlify.app/

Шаги воспроизведения:

1. Кликнуть на кнопку "Вход"
2. Ввести в поле Email: godmagik@yandex.ru.
3. Ввести в поле пароль 6 пробелов.

Ожидаемый результат: Система не принимает пробелы в поле пароль. Должна быть ошибка
Фактический результат: Система пропускает пробелы. 

Окружение:
ОС: Windows 10 Home Single Language 10.0.19045.3570
Разрешение: 1920х1080

Браузер:

1. Google Chrome Версия 119.0.6045.124 (64 бит)
2. Яндекс Браузер Версия 23.9.4.837 (64-bit)

Дополнительные материалы:

https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/147543438/30786a36-5a2b-4ef9-b258-2a425fea0bc0

![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/147543438/c412761c-727a-4966-b428-721f77fefeb4)

**Comment by Kampel2012** [comment]
![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/117913798/9c546786-deb6-42f4-a465-4eb2a1cc403d)
Fix: паттерн пароля
