### ISSUE TITLE
[Minor](Авторизация). При вводе 6 пробелов в поле "Пароль", кнопка "Вход" активная в поп-ап.

### ISSUE THREAD

**Issue by sergeev-aleksey** [a-platform-for-designers/a-platform-for-designers-frontend#77]
Серьёзность: Minor.

Предусловие:

Открыть тестовый стенд по ссылке https://pre-dev-qa-11-11-2023--peppy-cucurucho-6ce816.netlify.app/

Шаги воспроизведения:

1. Кликнуть на кнопку "Вход"
2. Ввести в поле Email: godmagik@yandex.ru
3. Ввести в поле пароль 6 пробелов.

Ожидаемый результат: Кнопка "Вход" не активна
Фактический результат: Кнопка "Вход" активна.

Окружение:
ОС: Windows 10 Home Single Language 10.0.19045.3570
Разрешение: 1920х1080

Браузер:

1. Google Chrome Версия 119.0.6045.124 (64 бит)
2. Яндекс Браузер Версия 23.9.4.837 (64-bit)
3. Mozilla Firefox Версия 119.0.1 (64-разрядный)

Дополнительные материалы:

![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/147543438/2e7d9247-5304-4182-a05c-7b6a2344f63b)

**Comment by Kampel2012** [comment]
Fix, проверка длины пароля теперь 8 символов  P.s. на 8 пробелах будет ошибка "Используйте латиницу, цифры или спецсимволы"
![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/117913798/c4a39085-91a2-4a2e-9cef-23c53438cab7) 
![image](https://github.com/a-platform-for-designers/a-platform-for-designers-frontend/assets/117913798/db0eba39-dfb3-4b22-a695-5d1acca53327)
